"""F5-Q2A-R3 independent verifier core. GENERATED by r3_tools/gen_verifier.py: every function below is copied VERBATIM from
the frozen R2 FINAL science checker (f5_q2a_science_checker/check.py, sha256 d02d2c206411f6f6adf557e697ab0e73c4570f4ae4e04c7bdafd381b46a1b841) - the independent recomputation that was
differentially qualified (exact agreement) against the frozen primary analysis. Only the constants block is re-declared for
the R3 namespaces. This module imports NO project package (stdlib + scipy.stats only)."""
import ast
import glob
import hashlib
import json
import math
import os
import re

from scipy import stats

CONDITIONS = {"S0A": ["A"], "S0B": ["B"], "S1": ["A", "B"], "S2": ["B", "A"], "S3": ["A", "B", "A"], "S4": ["B", "A", "B"]}
RELATIONS = ("R_POS", "R_ZERO", "R_NEG")
CONTRASTS = (("R_POS", "R_ZERO"), ("R_NEG", "R_ZERO"), ("R_POS", "R_NEG"))
SUBTYPES = {"INITIALIZATION": ("JUMPSTART_A_TO_B", "JUMPSTART_B_TO_A"), "LEARNING": ("LEARN_AULC_A_TO_B", "LEARN_AULC_B_TO_A"),
            "TOTAL": ("AULC_A_TO_B", "AULC_B_TO_A"), "BACKWARD_INTERFERENCE": ("BI_B_ON_A", "BI_A_ON_B")}
REQUIRED_DESIGN = ("T_PHASE", "CKPT_EVERY", "BATCH", "K_LATENT", "DEV_INDEPENDENT_WORLDS")
FORBIDDEN_TOKENS = ("pos", "neg", "zero", "r_")
HEAD_COS_THRESHOLD = 0.8
SCIENCE_MODES = ("authorized",)
RAW_NAME = re.compile(r"^RAW_WORLD_(\d{4})\.json$")
MODE_NAMESPACE = {}          # filled per run by verify.py from the verified handoff (qual / fixture / authorized namespace)


class FailClosed(Exception):
    pass


def _sha_bytes(b):
    return hashlib.sha256(b).hexdigest()


def _sha(p):
    with open(p, "rb") as f:
        return _sha_bytes(f.read())


def _load_json(p):
    if not os.path.isfile(p):
        raise FailClosed("missing file: %s" % os.path.basename(p))
    try:
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        raise FailClosed("malformed JSON: %s" % os.path.basename(p))


def _finite(x, what):
    if not isinstance(x, (int, float)) or isinstance(x, bool) or not math.isfinite(x):
        raise FailClosed("non-finite or non-numeric value in %s" % what)
    return float(x)


def _is_int(x):
    return type(x) is int


def design_constants(path):
    src = open(path, encoding="utf-8").read()
    out = {}
    for n in ast.parse(src).body:
        if isinstance(n, ast.Assign) and len(n.targets) == 1 and isinstance(n.targets[0], ast.Name) and isinstance(n.value, ast.Constant):
            out[n.targets[0].id] = n.value.value
    if any(k not in out for k in REQUIRED_DESIGN):
        raise FailClosed("design file lacks required constants")
    return out


def tci(v):
    n = len(v)
    m = sum(v) / n
    if n < 2:
        return {"n": n, "mean": m, "ci95": [float("nan"), float("nan")], "p": float("nan")}
    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (n - 1))
    se = sd / math.sqrt(n)
    q = float(stats.t.ppf(0.975, n - 1))
    p = float(2 * stats.t.sf(abs(m) / se, n - 1)) if se > 0 else (0.0 if m != 0 else 1.0)
    return {"n": n, "mean": m, "ci95": [m - q * se, m + q * se], "p": p}


def holm(cells):
    keys = sorted(cells, key=lambda k: (math.isnan(cells[k]["p"]), cells[k]["p"]))
    stop = False
    for i, k in enumerate(keys):
        c = cells[k]
        ok = (not stop) and not math.isnan(c["p"]) and c["p"] <= 0.05 / (len(keys) - i)
        stop = stop or not ok
        c["holm"] = ok
        c["class"] = "POSITIVE" if ok and c["ci95"][0] > 0 else "NEGATIVE" if ok and c["ci95"][1] < 0 else "NOT_DETECTED"
    return cells


def label(subtype, c1, c2):
    if subtype == "BACKWARD_INTERFERENCE":
        if c1 == c2 == "POSITIVE":
            return "ABSOLUTE_BI_RISE_DETECTED"
        return "ABSOLUTE_BI_RISE_NOT_DETECTED" if "POSITIVE" not in (c1, c2) else "ABSOLUTE_BI_ASYMMETRIC"
    pos, neg = {"INITIALIZATION": ("INITIALIZATION_BENEFIT", "INITIALIZATION_INTERFERENCE"), "LEARNING": ("LEARNING_BENEFIT", "LEARNING_INTERFERENCE"),
                "TOTAL": ("POSITIVE_TRANSFER", "NEGATIVE_TRANSFER")}[subtype]
    if c1 == c2 == "POSITIVE":
        return pos
    if c1 == c2 == "NEGATIVE":
        return neg
    return "NO_DETECTED_TRANSFER" if c1 == c2 == "NOT_DETECTED" else "DIRECTION_ASYMMETRIC"


def _fingerprints(w):
    out = set()
    for p in w["pairs"].values():
        for c, r in p.items():
            if "failure" in r:
                continue
            out.add("init:" + str(r["init_digest"]))
            out.update("end:" + str(x["end_param_digest"]) for x in r["phases"])
        for c, role in (("S0A", "A"), ("S0B", "B")):
            if "failure" not in p[c]:
                out.add("curve:" + _sha_bytes(json.dumps(p[c]["phases"][0]["curve"][role]).encode()))
    return out


def verify_evidence(run, expected_sha, mode):
    if mode in SCIENCE_MODES and os.path.lexists(os.path.join(run, "analysis")):
        raise FailClosed("primary analysis output exists before the science checker ran")
    for r, ds, fs in os.walk(run):
        for x in ds + fs:
            p = os.path.join(r, x)
            if os.path.islink(p) or os.path.isjunction(p) or (os.path.isfile(p) and os.stat(p).st_nlink > 1):
                raise FailClosed("link, junction or hard-linked file inside the evidence: %s" % x)
        ds[:] = [d for d in ds if os.path.relpath(os.path.join(r, d), run).replace("\\", "/") != "analysis"]
    sums = os.path.join(run, "SHA256SUMS")
    if not os.path.isfile(sums):
        raise FailClosed("missing SHA256SUMS")
    listed = {}
    for line in open(sums, encoding="utf-8"):
        if not line.strip():
            continue
        h, f = line.rstrip("\n").split("  ", 1)
        if f.startswith("analysis/"):
            raise FailClosed("SHA256SUMS lists analysis output")
        p = os.path.join(run, f)
        if not os.path.isfile(p) or _sha(p) != h:
            raise FailClosed("evidence hash mismatch or missing: %s" % f)
        listed[f] = h
    m = _load_json(os.path.join(run, "EVIDENCE_MANIFEST.json"))
    body = {k: v for k, v in m.items() if k != "evidence_manifest_sha256"}
    if _sha_bytes(json.dumps(body, sort_keys=True).encode()) != m.get("evidence_manifest_sha256"):
        raise FailClosed("evidence manifest self-hash mismatch")
    if m.get("evidence_manifest_sha256") != expected_sha:
        raise FailClosed("evidence manifest differs from the expected (reported) evidence manifest hash")
    if m.get("files") != {k: v for k, v in listed.items() if k != "EVIDENCE_MANIFEST.json"}:
        raise FailClosed("evidence manifest and SHA256SUMS disagree")
    on_disk = set()
    for r, ds, fs in os.walk(run):
        ds[:] = [d for d in ds if os.path.relpath(os.path.join(r, d), run).replace("\\", "/") != "analysis"]
        for f in fs:
            rel = os.path.relpath(os.path.join(r, f), run).replace("\\", "/")
            if rel != "SHA256SUMS":
                on_disk.add(rel)
    if on_disk != set(listed):
        raise FailClosed("unlisted or missing evidence files")
    return m


def load_worlds(run, n, mode, design):
    ctr = _load_json(os.path.join(run, "EXECUTION_COUNTER.json"))
    summ = _load_json(os.path.join(run, "RUN_SUMMARY.json"))
    fails = _load_json(os.path.join(run, "FAILURE_REGISTRY.json"))
    if ctr.get("mode") != mode or summ.get("mode") != mode:
        raise FailClosed("execution mode mismatch")
    if ctr.get("namespace") != MODE_NAMESPACE[mode] or summ.get("namespace") != MODE_NAMESPACE[mode]:
        raise FailClosed("namespace does not match mode %s" % mode)
    if mode in SCIENCE_MODES and not (isinstance(ctr.get("authorization_id"), str) and ctr["authorization_id"]):
        raise FailClosed("science evidence without an authorization id")
    if not isinstance(fails, dict) or not isinstance(fails.get("failures"), list):
        raise FailClosed("malformed failure registry")
    units = ctr.get("units")
    if not isinstance(units, list) or not all(_is_int(u) for u in units) or len(units) != n or len(set(units)) != n or \
            summ.get("units_expected") != units:
        raise FailClosed("world count / unit list inconsistent with n=%d" % n)
    if summ.get("units_done") != units or summ.get("failures") != len(fails["failures"]):
        raise FailClosed("run summary inconsistent with the unit list or the failure registry")
    raw_files = sorted(glob.glob(os.path.join(run, "RAW_WORLD_*")))
    if any(not RAW_NAME.match(os.path.basename(p)) for p in raw_files):
        raise FailClosed("malformed RAW_WORLD file name")
    if len(raw_files) != n or len(glob.glob(os.path.join(run, "HIDDEN_TRUTH_*"))) != n:
        raise FailClosed("missing or extra world(s): %d RAW_WORLD files for n=%d" % (len(raw_files), n))
    T, CK, B_EX = design["T_PHASE"], design["CKPT_EVERY"], design["T_PHASE"] * design["BATCH"]
    n_ck = T // CK + 1
    registered = {(f.get("unit"), f.get("pair"), f.get("condition")) for f in fails["failures"] if isinstance(f, dict)}
    worlds, seen, anchors, prints = {}, set(), set(), {}
    for p in raw_files:
        u_file = int(RAW_NAME.match(os.path.basename(p)).group(1))
        w = _load_json(p)
        h = _load_json(os.path.join(run, "HIDDEN_TRUTH_%04d.json" % u_file))
        u = w.get("unit")
        if u != u_file or u in seen or u not in units:
            raise FailClosed("duplicate or mislabelled world: file %04d unit %r" % (u_file, u))
        seen.add(u)
        if w.get("anchor") in anchors:
            raise FailClosed("duplicate world content (anchor repeated) at unit %d" % u)
        anchors.add(w.get("anchor"))
        rel = h.get("relations")
        if not isinstance(rel, dict) or sorted(rel.values()) != sorted(RELATIONS):
            raise FailClosed("unknown or missing relation in world %d" % u)
        if set(w.get("pairs", {})) != set(rel) or h.get("anchor") != w.get("anchor"):
            raise FailClosed("inconsistent pair mapping in world %d" % u)
        eval_work = set()
        for pid, pair in w["pairs"].items():
            if set(pair) != set(CONDITIONS):
                raise FailClosed("unknown or missing condition in world %d" % u)
            for c, r in pair.items():
                if "failure" in r:
                    if (u, pid, c) not in registered:
                        raise FailClosed("condition failure not in the failure registry: world %d %s" % (u, c))
                    continue
                if r.get("task_ids") != {"A": w["anchor"], "B": pid}:
                    raise FailClosed("inconsistent task mapping in world %d" % u)
                ph = r.get("phases")
                if not isinstance(ph, list) or len(ph) != len(CONDITIONS[c]) or "init_digest" not in r:
                    raise FailClosed("partial phases in world %d %s" % (u, c))
                for i, x in enumerate(ph):
                    for key in ("curve", "train_examples", "eval_awu", "end_param_digest", "train_role"):
                        if key not in x:
                            raise FailClosed("partial metrics in world %d %s" % (u, c))
                    _finite(x["train_examples"], "train_examples world %d %s" % (u, c))
                    _finite(x["eval_awu"], "eval_awu world %d %s" % (u, c))
                    if x["train_examples"] != B_EX:
                        raise FailClosed("phase exposure differs from the frozen T_PHASE*BATCH in world %d %s" % (u, c))
                    if x["train_role"] != CONDITIONS[c][i]:
                        raise FailClosed("train_role does not match condition %s in world %d" % (c, u))
                    eval_work.add(x["eval_awu"])
                    for role in ("A", "B"):
                        if role not in x["curve"] or not isinstance(x["curve"][role], list) or not x["curve"][role]:
                            raise FailClosed("partial curve in world %d %s" % (u, c))
                        for v in x["curve"][role]:
                            _finite(v, "curve world %d %s" % (u, c))
            m = h.get("measured", {}).get(pid)
            if not m or not isinstance(m.get("principal_cosines"), list) or len(m["principal_cosines"]) != design["K_LATENT"] or "declared" not in m:
                raise FailClosed("hidden truth measurements missing in world %d" % u)
            for v in m["principal_cosines"] + ([] if m.get("head_cosine_if_shared") is None else [m["head_cosine_if_shared"]]):
                _finite(v, "hidden truth world %d" % u)
        if len(eval_work) > 1:
            raise FailClosed("evaluator work differs between phases in world %d" % u)
        fp = _fingerprints(w)
        for u2, fp2 in prints.items():
            if fp & fp2:
                raise FailClosed("duplicate world content: worlds %d and %d share digests or curves" % (u2, u))
        prints[u] = fp
        worlds[u] = (w, h)
    return worlds, fails, n_ck, ctr


def recompute(worlds, fails, n_ck, n):
    """Gates are exactly the frozen primary gates (f5_q2a analysis.main)."""
    aul = lambda c: sum(c) / len(c)
    g = {"zero_failures": len(fails["failures"]) == 0, "determinism_and_pairing": True, "hidden_truth_verified": True,
         "equal_exposure": True, "identical_evaluator_schedule": True, "no_task_id_relation_tokens": True}
    rows = []
    for u, (w, h) in sorted(worlds.items()):
        by = {}
        for pid, p in w["pairs"].items():
            r = h["relations"][pid]
            g["no_task_id_relation_tokens"] &= not any(t in pid.lower() for t in FORBIDDEN_TOKENS)
            if any("failure" in c for c in p.values()):
                g["determinism_and_pairing"] = False
                continue
            S = {c: p[c]["phases"] for c in CONDITIONS}
            g["determinism_and_pairing"] &= ([x["end_param_digest"] for x in S["S3"][:2]] == [x["end_param_digest"] for x in S["S1"]] and
                                             [x["end_param_digest"] for x in S["S4"][:2]] == [x["end_param_digest"] for x in S["S2"]] and
                                             S["S1"][0]["end_param_digest"] == S["S0A"][0]["end_param_digest"] and
                                             S["S2"][0]["end_param_digest"] == S["S0B"][0]["end_param_digest"] and
                                             len({p[c]["init_digest"] for c in CONDITIONS}) == 1)
            ex = {c: sum(x["train_examples"] for x in S[c]) for c in CONDITIONS}
            g["equal_exposure"] &= (ex["S1"] == ex["S2"] == 2 * ex["S0A"] == 2 * ex["S0B"] and ex["S3"] == ex["S4"] == 3 * ex["S0A"])
            g["identical_evaluator_schedule"] &= all(len(x["curve"][k]) == n_ck for c in CONDITIONS for x in S[c] for k in ("A", "B"))
            m = h["measured"][pid]
            shared = all(abs(c - 1) < 1e-9 for c in m["principal_cosines"])
            hc = m.get("head_cosine_if_shared")
            g["hidden_truth_verified"] &= {"R_POS": shared and hc is not None and hc > HEAD_COS_THRESHOLD,
                                           "R_NEG": shared and hc is not None and hc < -HEAD_COS_THRESHOLD, "R_ZERO": not shared}[r]
            s0a, s0b, s1, s2 = S["S0A"][0]["curve"], S["S0B"][0]["curve"], S["S1"], S["S2"]
            by[r] = {"JUMPSTART_A_TO_B": s0b["B"][0] - s1[1]["curve"]["B"][0], "JUMPSTART_B_TO_A": s0a["A"][0] - s2[1]["curve"]["A"][0],
                     "LEARN_AULC_A_TO_B": aul(s0b["B"][1:]) - aul(s1[1]["curve"]["B"][1:]), "LEARN_AULC_B_TO_A": aul(s0a["A"][1:]) - aul(s2[1]["curve"]["A"][1:]),
                     "AULC_A_TO_B": aul(s0b["B"]) - aul(s1[1]["curve"]["B"]), "AULC_B_TO_A": aul(s0a["A"]) - aul(s2[1]["curve"]["A"]),
                     "BI_B_ON_A": s1[1]["curve"]["A"][-1] - s1[0]["curve"]["A"][-1], "BI_A_ON_B": s2[1]["curve"]["B"][-1] - s2[0]["curve"]["B"][-1],
                     "SCRATCH_AULC_B": aul(s0b["B"])}
        if set(by) == set(RELATIONS):
            rows.append(by)
    diff = holm({"%s-%s|SCRATCH_AULC_B" % (a, b): tci([x[a]["SCRATCH_AULC_B"] - x[b]["SCRATCH_AULC_B"] for x in rows]) for a, b in CONTRASTS}) if rows else {}
    g["marginal_difficulty_balance_not_detected"] = bool(diff) and all(c["class"] == "NOT_DETECTED" for c in diff.values())
    g["all_worlds_complete"] = len(rows) == len(worlds) == n and len(rows) >= 2
    absolute, contrasts, labels = {}, {}, {}
    if len(rows) >= 2:
        for s, ds in SUBTYPES.items():
            absolute[s] = {d: holm({r: tci([x[r][d] for x in rows]) for r in RELATIONS}) for d in ds}
            contrasts[s] = {d: holm({"%s-%s" % (a, b): tci([x[a][d] - x[b][d] for x in rows]) for a, b in CONTRASTS}) for d in ds}
            labels[s] = {r: label(s, absolute[s][ds[0]][r]["class"], absolute[s][ds[1]][r]["class"]) for r in RELATIONS}
    gates_ok = all(g.values())
    detail, qual = {}, []
    for s in ("INITIALIZATION", "LEARNING", "BACKWARD_INTERFERENCE"):
        if not contrasts:
            break
        d1, d2 = SUBTYPES[s]
        per = {}
        for d in (d1, d2):
            B = any(c["class"] != "NOT_DETECTED" for c in contrasts[s][d].values())
            D = None if s == "BACKWARD_INTERFERENCE" else ("POSITIVE" in [c["class"] for c in absolute[s][d].values()] and
                                                          "NEGATIVE" in [c["class"] for c in absolute[s][d].values()])
            per[d] = {"B": B, "D": D, "meets": B and (D if D is not None else True)}
        if s == "BACKWARD_INTERFERENCE":
            same = [k for k in contrasts[s][d1] if contrasts[s][d1][k]["class"] != "NOT_DETECTED" and contrasts[s][d1][k]["class"] == contrasts[s][d2][k]["class"]]
            q = per[d1]["B"] and per[d2]["B"] and bool(same)
        else:
            q = per[d1]["meets"] and per[d2]["meets"]
        coarse = all(contrasts[s][d]["R_POS-R_NEG"]["class"] != "NOT_DETECTED" for d in (d1, d2))
        detail[s] = {"qualifies": q, "per_direction": per, "coarse_relevance_challenge": coarse}
        if q:
            qual.append(s)
    if not gates_ok:
        state, sub = "DESIGN_NO_INFERENCE", None
    elif qual:
        state, sub = "SELECTIVE_CONTROL_OPPORTUNITY_PRESENT", (qual[0] if len(qual) == 1 else "MULTIPLE")
    else:
        state, sub = "SELECTIVE_CONTROL_OPPORTUNITY_NOT_DETECTED", None
    return {"gates": g, "difficulty_balance": diff, "absolute": absolute, "contrasts": contrasts, "labels": labels,
            "opportunity_detail": detail, "state": state, "subtype": sub, "n_complete_worlds": len(rows)}
